### ISSUE TITLE
大佬： 线上演示地址无法登录进去

### ISSUE THREAD

**Issue by xianengqi** [weiximei/yqm-shop-admin#1]
大佬您好，项目写的真棒，已经star，今天访问线上地址报`接口请求失败`，这是线上地址`https://www.yqmshop.cn`

**Comment by weiximei** [comment]
从官方网站上点进去

**Comment by xianengqi** [comment]
线上的后台管理系统好像进不去`https://shop.yqmshop.cn/single/#/login?redirect=%2Fdashboard`

**Comment by weiximei** [comment]
![DF55CF63-EA4C-4D60-806C-769CD268C028](https://github.com/weiximei/yqm-shop-admin/assets/37061242/dda30def-b021-4b50-9d0c-cb51c0fbffe0)


可以登陆

也可以联系客服

**Comment by xianengqi** [comment]
线上地址访问进去就报`接口请求失败`，`https://shop.yqmshop.cn/single/#/login?redirect=%2Fdashboard`

**Comment by weiximei** [comment]
不要用https，用http

**Comment by xianengqi** [comment]
可以进去了，感谢大佬～，祝大佬日进斗金
